using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;
namespace DevGoose
{
    internal class Constants
    {
        public static string[] allitems = new string[]
			{
                //This list is everything apart from the pub rear tomatos, 3 umbrellas in high street and the tea cup.
                "boot",
                "drinkcan",
                "tennisball",
                "boltBent",
                "sandwichR",
                "sandwichL",
                "apple",
                "basket",
                "coin",
                "bowProp_b",
                "pintBottle",
                "pintBottle (1)",
                "SluiceGates/pintBottle",
                "dummyProp",
                "SluiceGates/boot",
                "exitParcel",
                "ExitLetter",
                "ConeProp",
                "FertilizerPile",
                "apple (1)",
                "radiosmall",
                "shovel",
                "keys",
                "gardenerHat",
                "strawhat",
                "tulip",
                "carrot",
                "carrot (1)",
                "carrot (2)",
                "carrot (3)",
                "carrot (4)",
                "carrot (5)",
                "carrot (18)",
                "carrot (19)",
                "carrot (17)",
                "carrot (16)",
                "potbig",
                "mallet",
                "rake",
                "cratewooden",
                "cabbage",
                "cabbage (2)",
                "cabbage (10)",
                "cabbage (11)",
                "pumpkin (4)",
                "pumpkin (2)",
                "pumpkin",
                "pumpkin (3)",
                "wateringcan",
                "jam",
                "thermos (1)",
                "picnicmug",
                "coolBox",
                "gumboot (2)",
                "gumboot (1)",
                "gardenersign",
                "football",
                "wimpGlasses",
                "chalk",
                "carrotNoGreen (2)",
                "carrotNoGreen (1)",
                "carrotNoGreen (3)",
                "pushbroomProp",
                "Fusilage",
                "GROUP_ShelvesStuff/dishwashBottle",
                "canOrange",
                "canYellow",
                "canBlue",
                "pricingGun",
                "forkGarden",
                "weedTool",
                "hairbrush",
                "toycar",
                "babyDoll",
                "stereoscope",
                "hornRimmedGlasses",
                "SunGlasses",
                "redGlasses",
                "lilyFlower",
                "addingMachine",
                "tomato (2)",
                "tomato (1)",
                "tomato (3)",
                "orange (2)",
                "orange",
                "orange (1)",
                "cucumber",
                "cucumber (2)",
                "cucumber (1)",
                "leek (2)",
                "leek (3)",
                "leek (1)",
                "walkieTalkieB",
                "walkieTalkie",
                "dustbinLid",
                "dustbinGroup/dustbin/dustbin",
                "sprayBottle",
                "appleCore (1)",
                "appleCore",
                "toothbrush",
                "toiletPaper",
                "BasketProp",
                "cricketBall",
                "cricketBat",
                "bustPipeProp",
                "bustHatProp",
                "bustGlassesProp",
                "CleanSlipperR",
                "CleanSlipperL",
                "teaPot",
                "newspaper",
                "cleanSignProp",
                "roseProp",
                "clippers",
                "GROUP_ClotheslineItems/braSkinned", //BROKE
                "socksPlaceholder (1)",
                "socksPlaceholder",
                "vaseProp",
                "bowProp",
                "duckStatueProp",
                "frogstatue",
                "jeremyFish",
                "soap",
                "drawer",
                "JugEnamel",
                "potStack",
                "paintbrush",
                "messysignProp",
                "badmintonRacket",
                "fishingBobberProp",
                "tackleboxProp",
                "woolyHat",
                "portableStool",
                "harmonica",
                "quoitGreen (1)",
                "quoitGreen",
                "quoitGreen (2)",
                "quoitRed (2)",
                "quoitRed",
                "quoitRed (1)",
                "flowerforVase", // Not Sure No Handle
                "plate (2)",
                "plate",
                "plate (1)",
                "PubTomato", // Find All PubTomato
                "FrontPubTomato",
                "FrontPubTomato (1)",
                "pubNoGoose",
                "stealthBox",
                "infiniteBox",
                "candlestick",
                "knife (1)",
                "knife",
                "fork (1)",
                "fork",
                "cork",
                "pintGlassProp",
                "pintGlassNoRespawn",
                "pintGlassNoRespawn (1)",
                "peppergrinder",
                "toyBoat",
                "pubWomanCloth",
                "mop",
                "mopBucket", 
                "pail", // IDK
                "dart3",
                "dart2",
                "dart1",
                "dartboard",
                "MiniPerson Variant - child",
                "MiniPerson Variant - jumpsuit",
                "MiniPerson Variant - goose",
                "miniBenchProp",// Teleports you
                "MiniPerson Variant - gardener",
                "miniShovelProp",
                "flowerPoppy",
                "miniPumpProp",// Teleports you
                "miniBenchStreetProp",// Teleports you
                "MiniPerson Variant - old woman",
                "miniPhoneDoorProp",// Teleports you
                //"Mini-HighStreet/miniMailPillar/miniMailPillarProp", //BROKE
                "MiniPerson Variant - postie",
                "birdbathProp",
                "easelProp", // Teleports you
                "sunloungeProp",// Teleports you
                "MiniPerson Variant - vestman",
                "MiniPerson",
                "TimberHandleProp",
                "goldenBell",
                "Present_lid",
                "Present_box",
                "crown",
                "present_shoelid",
                "present_shoebox",
                "crownPaper",
			};
    }
}
