using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;
namespace DevGoose
{
    internal class Constants
    {
        public static string[] allitems = new string[]
			{
				"boot",
				"drinkcan",
				"tennisball",
				"boltBent",
				"sandwichR",
				"sandwichL",
				"apple",
				"basket",
				"coin",
				//"bow",
				"pintBottle",
				"dummyProp",
				"exitParcel",
				"ExitLetter",
				"ConeProp",
				"FertilizerPile",
				//"gardener",
				"radiosmall",
				"shovel",
				"keys",
				"gardenerHat",
				"strawhat",
				"tulip",
				"carrot",
				"potbig",
				"mallet",
				"rake",
				"cratewooden",
				//"cabbage (1)", // needs fix NOPE
				"pumpkin",
				"wateringcan",
				"jam",
				"thermos (1)",
				"picnicmug",
				"coolBox",
				"gumboot (2)",
				"gardenersign", // hmm
				//"potbig",
				"football",
				//"wimp",
				//"tvshop brain",
				"wimpGlasses",
				"chalk",
				"carrotNoGreen (1)",
				"pushbroomProp",
				"Fusilage",
				//"dishwashBottle", // NEED FIX
				"canOrange",
				"canYellow",
				"canBlue",
				"pricingGun",
				"forkGarden",
				"weedTool",
				"umbrella", // NF umbrella
				"hairbrush",
				"toycar",
				"babyDoll",
				"stereoscope",
				//"shopkeeper",
				"hornRimmedGlasses",
				"SunGlasses",
				"redGlasses",
				"lilyFlower",
				"addingMachine",
				"tomato (1)",
				"orange",
				"cucumber",
				"leek (1)",
				"walkieTalkieB",
				"walkieTalkie",
				"dustbinLid",
				//"dustbin", //NF dustBinRotatedColliders
				"sprayBottle",
				"appleCore",
				"toothbrush",
				"toiletPaper",
				"BasketProp",
				//"neighbourclean", //neighbourClean neighbourclean
				//"neighbourmessyFIXED", // neighbourmessyFixed neighbourmessyFIXED
				"cricketBall",
				"cricketBat",
				"bustPipeProp",
				"bustHatProp",
				"bustGlassesProp",
				//"CleanSlipperR",
				//"CleanSlipperL",
				"teaPot",
				//"teaCup", // NF 
				"newspaper",
				"cleanSignProp",
				"roseProp",
				"clippers",
				//"braSkinned", //janky
				"socksPlaceholder (1)",
				"socksPlaceholder",
				"vaseProp",
				"bowProp",
				"duckStatueProp",
				"frogstatue",
				"jeremyFish",
				"soap",
				"drawer",
				"JugEnamel",
				"potStack",
				"paintbrush",
				"messysignProp",
				"badmintonRacket",
				"fishingBobberProp",
				"tackleboxProp",
				"woolyHat",
				"portableStool",
				"harmonica",
				"quoitGreen",
				"quoitRed",
				"flowerforVase",
				"plate",
				//"cook brain",
				//"pub man brain",
				//"pub woman brain",
				"PubTomato",
				"pubNoGoose",
				"stealthBox",
				"infiniteBox",
				"candlestick",
				"knife",
				"fork",
				"cork",
				"pintGlassProp",
				"peppergrinder",
				"toyBoat",
				"pubWomanCloth",
				"mopProp",
				"mopBucket",
				"pail",
				//"oldMan",
				"dart3",
				"dart2",
				"dart1",
				"dartboard",
				//"gossip1 brain",
				//"gossip2 brain",
				"MiniPerson Variant - child",
				"MiniPerson Variant - jumpsuit",
				"MiniPerson Variant - goose",
				//"miniBenchProp",
				"MiniPerson Variant - gardener",
				"miniShovelProp",
				"flowerPoppy",
				//"miniPumpProp",
				//"miniBenchStreetProp",
				"MiniPerson Variant - old woman",
				"phoneDoor",
				"miniMailPillarProp",
				"MiniPerson Variant - postie",
				//"birdbathProp",
				//"easelProp",
				//"sunloungeProp",
				"MiniPerson Variant - vestman",
				"MiniPerson",
				"TimberHandleProp",
				"goldenBell",
				"Present_lid",
				"presentBox", // Present_box
				"crown",
				"presentShoeBox", //  present_shoelid
				"present_shoebox",
				"crownPaper",
			};
    }
}
